### ISSUE TITLE
ImportError: No module named jubatus.classifier.client

### ISSUE THREAD

**Issue by andyyuan78** [jubatus/jubatus-tutorial-python#7]
ubgpu@ubgpu:~/github/jubatus/jubatus-tutorial-python$ jubaclassifier --name tutorial --configpath config.json
2015-06-19 02:43:31,262 10705 WARN  [server_util.cpp:134] "name" option is ignored
2015-06-19 02:43:31,263 10705 INFO  [server_util.cpp:371] starting jubaclassifier 0.7.2 RPC server at 64.104.168.66:9199
    pid                  : 10705
    user                 : ubgpu
    mode                 : standalone mode
    timeout              : 10
    thread               : 2
    datadir              : /tmp
    logdir               : 
    log config           : 

2015-06-19 02:43:31,263 10705 INFO  [server_util.cpp:128] load config from local file: /home/ubgpu/github/jubatus/jubatus-tutorial-python/config.json
2015-06-19 02:43:31,264 10705 INFO  [classifier_serv.cpp:113] config loaded: {
  "method": "PA",
  "converter": {
    "string_filter_types": {
      "detag": { "method": "regexp", "pattern": "<[^>]*>", "replace": "" }
    },
    "string_filter_rules": [
      { "key": "message", "type": "detag", "suffix": "-detagged" }
    ],
    "num_filter_types": {},
    "num_filter_rules": [],
    "string_types": {},
    "string_rules": [
      { "key": "message-detagged", "type": "space", "sample_weight": "bin", "global_weight": "bin"}
    ],
    "num_types": {},
    "num_rules": []
  },
  "parameter": {}
}

2015-06-19 02:43:31,265 10705 INFO  [server_helper.hpp:223] start listening at port 9199
2015-06-19 02:43:31,265 10705 INFO  [server_helper.hpp:230] jubaclassifier RPC server startup
.................

on another terminal:

ubgpu@ubgpu:~/github/jubatus/jubatus-tutorial-python$ sudo pip install jubatus 
[sudo] password for ubgpu: 
Requirement already satisfied (use --upgrade to upgrade): jubatus in /usr/local/lib/python2.7/dist-packages/jubatus-0.7.1-py2.7.egg
Requirement already satisfied (use --upgrade to upgrade): msgpack-rpc-python>=0.3.0 in /usr/local/lib/python2.7/dist-packages/msgpack_rpc_python-0.4-py2.7.egg (from jubatus)
Requirement already satisfied (use --upgrade to upgrade): msgpack-python in /usr/local/lib/python2.7/dist-packages/msgpack_python-0.4.6-py2.7-linux-x86_64.egg (from msgpack-rpc-python>=0.3.0->jubatus)
Requirement already satisfied (use --upgrade to upgrade): tornado>=3 in /usr/lib/python2.7/dist-packages (from msgpack-rpc-python>=0.3.0->jubatus)
ubgpu@ubgpu:~/github/jubatus/jubatus-tutorial-python$ 
ubgpu@ubgpu:~/github/jubatus/jubatus-tutorial-python$ python tutorial.py
Traceback (most recent call last):
  File "tutorial.py", line 6, in <module>
    from jubatus.classifier.client import Classifier
ImportError: No module named jubatus.classifier.client
ubgpu@ubgpu:~/github/jubatus/jubatus-tutorial-python$

**Comment by kmaehashi** [comment]
Please try this instead:

```
$ pip install jubatus
```

If it still doesn't work, maybe you have an odd python environment. To diagnose:

```
$ which pip
$ which python
$ pip show jubatus
$ python -c 'import sys; print(sys.path)'
```

**Comment by andyyuan78** [comment]
ubgpu@ubgpu:~/github/jubatus/jubatus-tutorial-python$ which pip
/usr/local/bin/pip
ubgpu@ubgpu:~/github/jubatus/jubatus-tutorial-python$ which python
/usr/bin/python
ubgpu@ubgpu:~/github/jubatus/jubatus-tutorial-python$ pip show jubatus
The directory '/home/ubgpu/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
---
Metadata-Version: 1.1
Name: jubatus
Version: 0.7.1
Summary: Jubatus is a distributed processing framework and streaming machine learning library. This is the Jubatus client in Python.
Home-page: http://jubat.us
Author: PFN & NTT
Author-email: jubatus@googlegroups.com
License: MIT License
Location: /usr/local/lib/python2.7/dist-packages/jubatus-0.7.1-py2.7.egg
Requires: msgpack-rpc-python
ubgpu@ubgpu:~/github/jubatus/jubatus-tutorial-python$ python -c 'import sys; print(sys.path)'
['', '/usr/lib/python2.7/dist-packages', '/usr/local/lib/python2.7/dist-packages/Lasagne-0.1dev-py2.7.egg', '/home/ubgpu/github/OpenDeep', '/home/ubgpu/src_theano/pylearn2', '/usr/local/lib/python2.7/dist-packages/emcee-2.1.0-py2.7.egg', '/home/ubgpu/github/crf_nlp/probablepeople', '/home/ubgpu/github/nlp_caffe/py-lmdb', '/usr/local/lib/python2.7/dist-packages/bumps-0.7.5.5-py2.7.egg', '/usr/local/lib/python2.7/dist-packages/hmmlearn-0.1.1-py2.7-linux-x86_64.egg', '/home/ubgpu/github/Mariana', '/usr/local/lib/python2.7/dist-packages/pyGeno-1.2.4-py2.7.egg', '/usr/local/lib/python2.7/dist-packages/rabaDB-1.0.1-py2.7.egg', '/usr/local/lib/python2.7/dist-packages/Keras-0.1.1-py2.7.egg', '/usr/local/lib/python2.7/dist-packages/jubatus-0.7.1-py2.7.egg', '/usr/local/lib/python2.7/dist-packages/msgpack_rpc_python-0.4-py2.7.egg', '/usr/local/lib/python2.7/dist-packages/msgpack_python-0.4.6-py2.7-linux-x86_64.egg', '/usr/local/lib/python2.7/dist-packages', '/usr/lib/python2.7', '/usr/lib/python2.7/plat-x86_64-linux-gnu', '/usr/lib/python2.7/lib-tk', '/usr/lib/python2.7/lib-old', '/usr/lib/python2.7/lib-dynload', '/usr/local/lib/python2.7/dist-packages/PIL', '/usr/lib/python2.7/dist-packages/PILcompat', '/usr/lib/python2.7/dist-packages/gtk-2.0', '/usr/lib/pymodules/python2.7', '/usr/lib/python2.7/dist-packages/ubuntu-sso-client']
ubgpu@ubgpu:~/github/jubatus/jubatus-tutorial-python$

**Comment by kmaehashi** [comment]
Hmm, it seems that your Python environment is odd.
The `pip` command is located under `/usr/local`, whereas `python` command is located under `/usr`.

If you're on Ubuntu-like systems, you can try:

```
sudo apt-get install python-pip
/usr/bin/pip install jubatus
```

to workaround the situation.

**Comment by kmaehashi** [comment]
Please reopen if the problem persists.
